config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rootmap/', include('rootmap.urls')),
    path('', RedirectView.as_view(url='/rootmap/'))
]

rootmap/urls.py
from django.urls import path
from . import views

app_name = 'rootmap'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('create', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update', views.UpdateView.as_view(), name='update'),
]

rootmap/models.py
from unicodedata import category
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
class Shop(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

rootmap/views.py
from dataclasses import field
from pyexpat import model
from django.shortcuts import render, redirect
from django.views import generic
from .models import Category, Shop

class IndexView(generic.ListView):
    model = Shop

class DetailView(generic.DetailView):
    model = Shop
    
class CreateView(generic.edit.CreateView):
    model = Shop
    fields = '__all__'
    
class UpdateView(generic.edit.UpdateView):
    model = Shop
    fields = '__all__'

rootmap/templates/rootmap/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>rootMap</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-md" style="padding: 10px;">
        <a href="{% url 'rootmap:index' %}" class="navbar-brand">ルート検索</a>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

rootmap/templates/rootmap/shop_detail.html
{% extends 'rootmap/base.html' %}

{% block content %}
<div style="padding: 20px;"></div>
<h1>{{shop.name}}</h1>
<div>
    <p>{{shop.category.name}}</p>
    <p>{{shop.address}}</p>
</div>
<div>
    <a href="{% url 'rootmap:index' %}">一覧へ戻る</a>
    <a href="{% url 'rootmap:upddate' shop.pk%}">内容を更新</a>
</div>
{% endblock %}

rootmap/templates/rootmap/shop_form.html
{% extends 'rootmap/base.html' %}

{% block content %}
<div style="padding: 20px;"></div>
<h1>お店情報の{{ object|yesno:'更新,作成' }}</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="submit">{{ object|yesno:'更新,作成' }}</button>
</form>

<div>
    <a href="JavaScript:history.back()">&lt; 戻る</a>
</div>
{% endblock %}

rootmap/templates/rootmap/shop_list.html
{% extends 'rootmap/base.html' %}

{% block content %}
<div style="padding-top: 20px;">
    <h1>お店一覧</h1>
    <table class="table table-striped table-hover">
        <tr>
            <th>カテゴリー</th><th>店名</th><th>住所</th>
        </tr>
        {% for shop in object_list %}
            <tr>
                <td>{{shop.category.name}}</td>
                <td><a href="{% url 'rootmap:detail' shop.pk%}">{{shop.name}}</a></td>
                <td>{{shop.address}}</td>
            </tr>
        {% endfor %}
    </table>
</div>
<div>
    <a href="{% url 'rootmap:create' %}">新しいお店</a>
</div>
{% endblock %}